# -*- coding: utf-8 -*-
"""augmentasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMggLaYchQUATBlB1gXhLgFYsOJHM6-i

# **JAHE**
"""

import os
import random
from PIL import Image, ImageEnhance

# Direktori input dan output
input_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Jahe"
output_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Jahe/jahe_augment"

# Membuat direktori output jika belum ada
os.makedirs(output_folder, exist_ok=True)

# Fungsi untuk melakukan augmentasi
def random_augment_image(image):
    augmented_images = []

    # Flip horizontal
    flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
    augmented_images.append(flipped)

    # Rotate +15
    rotated_plus = image.rotate(15, expand=True)
    augmented_images.append(rotated_plus)

    # Rotate -15
    rotated_minus = image.rotate(-15, expand=True)
    augmented_images.append(rotated_minus)

    # Brightness +15%
    enhancer = ImageEnhance.Brightness(image)
    brightened_plus = enhancer.enhance(1.15)  # +15%
    augmented_images.append(brightened_plus)

    # Brightness -15%
    brightened_minus = enhancer.enhance(0.85)  # -15%
    augmented_images.append(brightened_minus)

    # Pilih satu augmentasi secara acak
    return random.choice(augmented_images)

# Proses gambar dalam folder
count = 1
for file_name in os.listdir(input_folder):
    if file_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        # Membuka gambar
        image_path = os.path.join(input_folder, file_name)
        image = Image.open(image_path)

        # Menyimpan gambar asli ke folder output
        image_name = os.path.splitext(file_name)[0]
        original_save_path = os.path.join(output_folder, f"{image_name}_original_{count}.jpg")
        image.save(original_save_path)

        # Augmentasi gambar (1 augmentasi per gambar)
        augmented_image = random_augment_image(image)
        augmented_save_path = os.path.join(output_folder, f"{image_name}_augmented_{count}.jpg")
        augmented_image.save(augmented_save_path)

        count += 1
        if count > 50:  # Hentikan setelah 50 augmentasi tambahan
            break

print(f"Proses selesai. Gambar tersimpan di {output_folder}")

"""# **KENCUR**"""

import os
import random
from PIL import Image, ImageEnhance

# Direktori input dan output
input_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Kencur"
output_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Kencur/kencur_augment"

# Membuat direktori output jika belum ada
os.makedirs(output_folder, exist_ok=True)

# Fungsi untuk melakukan augmentasi
def random_augment_image(image):
    augmented_images = []

    # Flip horizontal
    flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
    augmented_images.append(flipped)

    # Rotate +15
    rotated_plus = image.rotate(15, expand=True)
    augmented_images.append(rotated_plus)

    # Rotate -15
    rotated_minus = image.rotate(-15, expand=True)
    augmented_images.append(rotated_minus)

    # Brightness +15%
    enhancer = ImageEnhance.Brightness(image)
    brightened_plus = enhancer.enhance(1.15)  # +15%
    augmented_images.append(brightened_plus)

    # Brightness -15%
    brightened_minus = enhancer.enhance(0.85)  # -15%
    augmented_images.append(brightened_minus)

    # Pilih satu augmentasi secara acak
    return random.choice(augmented_images)

# Proses gambar dalam folder
count = 1
for file_name in os.listdir(input_folder):
    if file_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        # Membuka gambar
        image_path = os.path.join(input_folder, file_name)
        image = Image.open(image_path)

        # Menyimpan gambar asli ke folder output
        image_name = os.path.splitext(file_name)[0]
        original_save_path = os.path.join(output_folder, f"{image_name}_original_{count}.jpg")
        image.save(original_save_path)

        # Augmentasi gambar (1 augmentasi per gambar)
        augmented_image = random_augment_image(image)
        augmented_save_path = os.path.join(output_folder, f"{image_name}_augmented_{count}.jpg")
        augmented_image.save(augmented_save_path)

        count += 1
        if count >= 50:  # Hentikan setelah 50 augmentasi tambahan
            break

print(f"Proses selesai. Gambar tersimpan di {output_folder}")

"""# **KUNCI**"""

import os
import random
from PIL import Image, ImageEnhance

# Direktori input dan output
input_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Kunci"
output_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Kunci/Kunci_augment"

# Membuat direktori output jika belum ada
os.makedirs(output_folder, exist_ok=True)

# Fungsi untuk melakukan augmentasi
def random_augment_image(image):
    augmented_images = []

    # Flip horizontal
    flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
    augmented_images.append(flipped)

    # Rotate +15
    rotated_plus = image.rotate(15, expand=True)
    augmented_images.append(rotated_plus)

    # Rotate -15
    rotated_minus = image.rotate(-15, expand=True)
    augmented_images.append(rotated_minus)

    # Brightness +15%
    enhancer = ImageEnhance.Brightness(image)
    brightened_plus = enhancer.enhance(1.15)  # +15%
    augmented_images.append(brightened_plus)

    # Brightness -15%
    brightened_minus = enhancer.enhance(0.85)  # -15%
    augmented_images.append(brightened_minus)

    # Pilih satu augmentasi secara acak
    return random.choice(augmented_images)

# Proses gambar dalam folder
count = 1
for file_name in os.listdir(input_folder):
    if file_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        # Membuka gambar
        image_path = os.path.join(input_folder, file_name)
        image = Image.open(image_path)

        # Menyimpan gambar asli ke folder output
        image_name = os.path.splitext(file_name)[0]
        original_save_path = os.path.join(output_folder, f"{image_name}_original_{count}.jpg")
        image.save(original_save_path)

        # Augmentasi gambar (1 augmentasi per gambar)
        augmented_image = random_augment_image(image)
        augmented_save_path = os.path.join(output_folder, f"{image_name}_augmented_{count}.jpg")
        augmented_image.save(augmented_save_path)

        count += 1
        if count >= 50:  # Hentikan setelah 50 augmentasi tambahan
            break

print(f"Proses selesai. Gambar tersimpan di {output_folder}")

"""# **KUNYIT**"""

import os
import random
from PIL import Image, ImageEnhance

# Direktori input dan output
input_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Kunyit "
output_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Kunyit /KUNYIT_AUGMENT"

# Membuat direktori output jika belum ada
os.makedirs(output_folder, exist_ok=True)

# Fungsi untuk melakukan augmentasi
def random_augment_image(image):
    augmented_images = []

    # Flip horizontal
    flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
    augmented_images.append(flipped)

    # Rotate +15
    rotated_plus = image.rotate(15, expand=True)
    augmented_images.append(rotated_plus)

    # Rotate -15
    rotated_minus = image.rotate(-15, expand=True)
    augmented_images.append(rotated_minus)

    # Brightness +15%
    enhancer = ImageEnhance.Brightness(image)
    brightened_plus = enhancer.enhance(1.15)  # +15%
    augmented_images.append(brightened_plus)

    # Brightness -15%
    brightened_minus = enhancer.enhance(0.85)  # -15%
    augmented_images.append(brightened_minus)

    # Pilih satu augmentasi secara acak
    return random.choice(augmented_images)

# Proses gambar dalam folder
count = 1
for file_name in os.listdir(input_folder):
    if file_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        # Membuka gambar
        image_path = os.path.join(input_folder, file_name)
        image = Image.open(image_path)

        # Menyimpan gambar asli ke folder output
        image_name = os.path.splitext(file_name)[0]
        original_save_path = os.path.join(output_folder, f"{image_name}_original_{count}.jpg")
        image.save(original_save_path)

        # Augmentasi gambar (1 augmentasi per gambar)
        augmented_image = random_augment_image(image)
        augmented_save_path = os.path.join(output_folder, f"{image_name}_augmented_{count}.jpg")
        augmented_image.save(augmented_save_path)

        count += 1
        if count >= 50:  # Hentikan setelah 50 augmentasi tambahan
            break

print(f"Proses selesai. Gambar tersimpan di {output_folder}")

"""# **KUNYIT PUTIH**"""

import os
import random
from PIL import Image, ImageEnhance

# Direktori input dan output
input_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Kunyit Putih"
output_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Kunyit Putih/kunyit_putih_augment"

# Membuat direktori output jika belum ada
os.makedirs(output_folder, exist_ok=True)

# Fungsi untuk melakukan augmentasi
def random_augment_image(image):
    augmented_images = []

    # Flip horizontal
    flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
    augmented_images.append(flipped)

    # Rotate +15
    rotated_plus = image.rotate(15, expand=True)
    augmented_images.append(rotated_plus)

    # Rotate -15
    rotated_minus = image.rotate(-15, expand=True)
    augmented_images.append(rotated_minus)

    # Brightness +15%
    enhancer = ImageEnhance.Brightness(image)
    brightened_plus = enhancer.enhance(1.15)  # +15%
    augmented_images.append(brightened_plus)

    # Brightness -15%
    brightened_minus = enhancer.enhance(0.85)  # -15%
    augmented_images.append(brightened_minus)

    # Pilih satu augmentasi secara acak
    return random.choice(augmented_images)

# Proses gambar dalam folder
count = 1
for file_name in os.listdir(input_folder):
    if file_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        # Membuka gambar
        image_path = os.path.join(input_folder, file_name)
        image = Image.open(image_path)

        # Menyimpan gambar asli ke folder output
        image_name = os.path.splitext(file_name)[0]
        original_save_path = os.path.join(output_folder, f"{image_name}_original_{count}.jpg")
        image.save(original_save_path)

        # Augmentasi gambar (1 augmentasi per gambar)
        augmented_image = random_augment_image(image)
        augmented_save_path = os.path.join(output_folder, f"{image_name}_augmented_{count}.jpg")
        augmented_image.save(augmented_save_path)

        count += 1
        if count >= 50:  # Hentikan setelah 50 augmentasi tambahan
            break

print(f"Proses selesai. Gambar tersimpan di {output_folder}")

"""# **LEMPUYANG**"""

import os
import random
from PIL import Image, ImageEnhance

# Direktori input dan output
input_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Lempuyang"
output_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Lempuyang/LEMPUYANG_AUGMENT"

# Membuat direktori output jika belum ada
os.makedirs(output_folder, exist_ok=True)

# Fungsi untuk melakukan augmentasi
def random_augment_image(image):
    augmented_images = []

    # Flip horizontal
    flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
    augmented_images.append(flipped)

    # Rotate +15
    rotated_plus = image.rotate(15, expand=True)
    augmented_images.append(rotated_plus)

    # Rotate -15
    rotated_minus = image.rotate(-15, expand=True)
    augmented_images.append(rotated_minus)

    # Brightness +15%
    enhancer = ImageEnhance.Brightness(image)
    brightened_plus = enhancer.enhance(1.15)  # +15%
    augmented_images.append(brightened_plus)

    # Brightness -15%
    brightened_minus = enhancer.enhance(0.85)  # -15%
    augmented_images.append(brightened_minus)

    # Pilih satu augmentasi secara acak
    return random.choice(augmented_images)

# Proses gambar dalam folder
count = 1
for file_name in os.listdir(input_folder):
    if file_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        # Membuka gambar
        image_path = os.path.join(input_folder, file_name)
        image = Image.open(image_path)

        # Menyimpan gambar asli ke folder output
        image_name = os.path.splitext(file_name)[0]
        original_save_path = os.path.join(output_folder, f"{image_name}_original_{count}.jpg")
        image.save(original_save_path)

        # Augmentasi gambar (1 augmentasi per gambar)
        augmented_image = random_augment_image(image)
        augmented_save_path = os.path.join(output_folder, f"{image_name}_augmented_{count}.jpg")
        augmented_image.save(augmented_save_path)

        count += 1
        if count >= 50:  # Hentikan setelah 50 augmentasi tambahan
            break

print(f"Proses selesai. Gambar tersimpan di {output_folder}")

"""# LENGKUAS"""

import os
import random
from PIL import Image, ImageEnhance

# Direktori input dan output
input_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Lengkuas"
output_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Lengkuas/LENGKUAS_AUGMENT"

# Membuat direktori output jika belum ada
os.makedirs(output_folder, exist_ok=True)

# Fungsi untuk melakukan augmentasi
def random_augment_image(image):
    augmented_images = []

    # Flip horizontal
    flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
    augmented_images.append(flipped)

    # Rotate +15
    rotated_plus = image.rotate(15, expand=True)
    augmented_images.append(rotated_plus)

    # Rotate -15
    rotated_minus = image.rotate(-15, expand=True)
    augmented_images.append(rotated_minus)

    # Brightness +15%
    enhancer = ImageEnhance.Brightness(image)
    brightened_plus = enhancer.enhance(1.15)  # +15%
    augmented_images.append(brightened_plus)

    # Brightness -15%
    brightened_minus = enhancer.enhance(0.85)  # -15%
    augmented_images.append(brightened_minus)

    # Pilih satu augmentasi secara acak
    return random.choice(augmented_images)

# Proses gambar dalam folder
count = 1
for file_name in os.listdir(input_folder):
    if file_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        # Membuka gambar
        image_path = os.path.join(input_folder, file_name)
        image = Image.open(image_path)

        # Menyimpan gambar asli ke folder output
        image_name = os.path.splitext(file_name)[0]
        original_save_path = os.path.join(output_folder, f"{image_name}_original_{count}.jpg")
        image.save(original_save_path)

        # Augmentasi gambar (1 augmentasi per gambar)
        augmented_image = random_augment_image(image)
        augmented_save_path = os.path.join(output_folder, f"{image_name}_augmented_{count}.jpg")
        augmented_image.save(augmented_save_path)

        count += 1
        if count >= 50:  # Hentikan setelah 50 augmentasi tambahan
            break

print(f"Proses selesai. Gambar tersimpan di {output_folder}")

"""# **TEMU IRENG**"""

import os
import random
from PIL import Image, ImageEnhance

# Direktori input dan output
input_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Temu Ireng"
output_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Temu Ireng/temuireng_augment"

# Membuat direktori output jika belum ada
os.makedirs(output_folder, exist_ok=True)

# Fungsi untuk melakukan augmentasi
def random_augment_image(image):
    augmented_images = []

    # Flip horizontal
    flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
    augmented_images.append(flipped)

    # Rotate +15
    rotated_plus = image.rotate(15, expand=True)
    augmented_images.append(rotated_plus)

    # Rotate -15
    rotated_minus = image.rotate(-15, expand=True)
    augmented_images.append(rotated_minus)

    # Brightness +15%
    enhancer = ImageEnhance.Brightness(image)
    brightened_plus = enhancer.enhance(1.15)  # +15%
    augmented_images.append(brightened_plus)

    # Brightness -15%
    brightened_minus = enhancer.enhance(0.85)  # -15%
    augmented_images.append(brightened_minus)

    # Pilih satu augmentasi secara acak
    return random.choice(augmented_images)

# Proses gambar dalam folder
count = 1
for file_name in os.listdir(input_folder):
    if file_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        # Membuka gambar
        image_path = os.path.join(input_folder, file_name)
        image = Image.open(image_path)

        # Menyimpan gambar asli ke folder output
        image_name = os.path.splitext(file_name)[0]
        original_save_path = os.path.join(output_folder, f"{image_name}_original_{count}.jpg")
        image.save(original_save_path)

        # Augmentasi gambar (1 augmentasi per gambar)
        augmented_image = random_augment_image(image)
        augmented_save_path = os.path.join(output_folder, f"{image_name}_augmented_{count}.jpg")
        augmented_image.save(augmented_save_path)

        count += 1
        if count >= 50:  # Hentikan setelah 50 augmentasi tambahan
            break

print(f"Proses selesai. Gambar tersimpan di {output_folder}")

"""# **TEMULAWAK**"""

import os
import random
from PIL import Image, ImageEnhance

# Direktori input dan output
input_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Temulawak"
output_folder = "/content/drive/MyDrive/MANDIRI_COMVIS/Temulawak/TEMULAWAK_AUGMENT"

# Membuat direktori output jika belum ada
os.makedirs(output_folder, exist_ok=True)

# Fungsi untuk melakukan augmentasi
def random_augment_image(image):
    augmented_images = []

    # Flip horizontal
    flipped = image.transpose(Image.FLIP_LEFT_RIGHT)
    augmented_images.append(flipped)

    # Rotate +15
    rotated_plus = image.rotate(15, expand=True)
    augmented_images.append(rotated_plus)

    # Rotate -15
    rotated_minus = image.rotate(-15, expand=True)
    augmented_images.append(rotated_minus)

    # Brightness +15%
    enhancer = ImageEnhance.Brightness(image)
    brightened_plus = enhancer.enhance(1.15)  # +15%
    augmented_images.append(brightened_plus)

    # Brightness -15%
    brightened_minus = enhancer.enhance(0.85)  # -15%
    augmented_images.append(brightened_minus)

    # Pilih satu augmentasi secara acak
    return random.choice(augmented_images)

# Proses gambar dalam folder
count = 1
for file_name in os.listdir(input_folder):
    if file_name.lower().endswith(('.png', '.jpg', '.jpeg')):
        # Membuka gambar
        image_path = os.path.join(input_folder, file_name)
        image = Image.open(image_path)

        # Menyimpan gambar asli ke folder output
        image_name = os.path.splitext(file_name)[0]
        original_save_path = os.path.join(output_folder, f"{image_name}_original_{count}.jpg")
        image.save(original_save_path)

        # Augmentasi gambar (1 augmentasi per gambar)
        augmented_image = random_augment_image(image)
        augmented_save_path = os.path.join(output_folder, f"{image_name}_augmented_{count}.jpg")
        augmented_image.save(augmented_save_path)

        count += 1
        if count >= 50:  # Hentikan setelah 50 augmentasi tambahan
            break

print(f"Proses selesai. Gambar tersimpan di {output_folder}")