# -*- coding: utf-8 -*-
"""rename.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19M7vbBG8jRYusOd6IeeNIWBRzlXF-tlf
"""

!pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

from googleapiclient.discovery import build
from google.oauth2 import service_account
import os

# File JSON service account (unduh dari Google Cloud Console)
SERVICE_ACCOUNT_FILE = '/content/drive/MyDrive/Colab Notebooks/credentials.json'
SCOPES = ['https://www.googleapis.com/auth/drive']

# Autentikasi Google Drive API
credentials = service_account.Credentials.from_service_account_file(
    SERVICE_ACCOUNT_FILE, scopes=SCOPES
)
drive_service = build('drive', 'v3', credentials=credentials)


def list_folders(parent_folder_id):
    """
    Mendapatkan daftar folder di dalam folder utama (comvis).
    """
    query = f"'{parent_folder_id}' in parents and mimeType = 'application/vnd.google-apps.folder'"
    results = drive_service.files().list(q=query, fields="files(id, name)").execute()
    return results.get('files', [])


def list_files_in_folder(folder_id):
    """
    Mendapatkan daftar file di dalam folder tertentu.
    """
    query = f"'{folder_id}' in parents and mimeType contains 'image/'"
    results = drive_service.files().list(q=query, fields="files(id, name)").execute()
    return results.get('files', [])


def rename_files_in_folder(folder_id, folder_name):
    """
    Merename file di dalam folder tertentu berdasarkan nama foldernya.
    """
    files = list_files_in_folder(folder_id)
    for index, file in enumerate(files, start=1):
        file_id = file['id']
        file_name = file['name']
        file_extension = os.path.splitext(file_name)[1]
        new_name = f"{folder_name}_{index}{file_extension}"

        # Update nama file di Google Drive
        drive_service.files().update(
            fileId=file_id,
            body={'name': new_name}
        ).execute()
        print(f"Renamed: {file_name} -> {new_name}")


def main():
    # ID folder utama 'comvis' (ganti dengan ID folder Google Drive Anda)
    parent_folder_id = '1kpLpQuzLFAraRyv3q2Ri2pL7MoD1WsIV'

    # List semua folder di dalam 'comvis'
    folders = list_folders(parent_folder_id)
    for folder in folders:
        folder_id = folder['id']
        folder_name = folder['name']
        print(f"Processing folder: {folder_name}")

        # Rename semua file di dalam folder
        rename_files_in_folder(folder_id, folder_name)


if __name__ == "__main__":
    main()